apiVersion: apps/v1
kind: Deployment
metadata:
  name: facility-deployment
  labels:
    app: facility
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facility
  template:
    metadata:
      labels:
        app: facility
    spec:
      containers:
      - name: facility-app
        image: facility_app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501